# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:23
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('venmo_username',
                 models.CharField(blank=True, max_length=50, unique=True, verbose_name="payer's venmo username")),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_pay_date', models.DateTimeField(null=True, verbose_name='last date the payer paid')),
                ('last_pay_amount',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                     verbose_name='last transaction amount')),
                ('next_pay_date', models.DateTimeField(null=True)),
                ('next_pay_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_due', models.DateTimeField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlanOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='transaction amount')),
                ('payer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                   to='api.Payer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venmo_handle', models.CharField(max_length=50)),
                ('venmo_auth_token', models.CharField(max_length=100)),
                ('venmo_refresh_token', models.CharField(max_length=100)),
                ('survey_code', models.CharField(default=api.models.SurveyCode, max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentplanoption',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans',
                                    to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payments', to='api.PaymentPlanOption'),
        ),
        migrations.AddField(
            model_name='payer',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers',
                                    to='api.PaymentPlanOption'),
        ),
        migrations.AddField(
            model_name='payer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers',
                                    to='api.UserProfile'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='transaction',
            order_with_respect_to='payer',
        ),
        migrations.AlterOrderWithRespectTo(
            name='paymentplanoption',
            order_with_respect_to='user_profile',
        ),
        migrations.AlterOrderWithRespectTo(
            name='payment',
            order_with_respect_to='payment_plan',
        ),
        migrations.AlterOrderWithRespectTo(
            name='payer',
            order_with_respect_to='user_profile',
        ),
    ]
