# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='venmo_auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='venmo_refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
